version: '3'

services:
    postgresql:
        image: postgres:13.2-alpine
        healthcheck:
          test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
          timeout: 45s
          interval: 10s
          retries: 10
        env_file: dev.env
        ports:
          - ${POSTGRES_PORT}:5432
        command: ["postgres", "-c", "log_statement=all"]
